# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

version: "3.3"

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    env_file:
      - dev_env.env
    ports:
      - "5000:5000"
    depends_on:
      - db
  test:
    build:
      context: .
      dockerfile: FCTest.Dockerfile
    volumes:
      - ".:/src"
    env_file:
    - test_env.env
    depends_on:
      - db
  prod:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ".:/src"
    env_file:
      - prod.env
    ports:
      - "5000:5000"
    depends_on:
      - db
  lint:
    build:
      context: .
      dockerfile: FCTest.Dockerfile
    volumes:
      - ".:/src"
    command: black /src/flight_club --check
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_dev_data:/var/lib/postgresql/dev_data/
    environment:
      - POSTGRES_USER=flight_club
      - POSTGRES_PASSWORD=flight_club
      - POSTGRES_DB=flight_club_dev
  proddb:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=flight_club
      - POSTGRES_PASSWORD=flight_club
      - POSTGRES_DB=flight_club_prod

volumes:
  postgres_dev_data:
  postgres_data:
  
